---
title: "Week 10.5 Exercises"
author: "Hu Tu"
date: '2023-04-23'
output:
  html_document:
    df_print: paged
---

```{r}
getwd()

```

# Load Data
```{r}
data <- read.csv("./archive/student-mat.csv")
head(data)
str(data)
```


```{r}
data$school <- as.factor(data$school)
data$sex <- as.factor(data$sex)
data$address <- as.factor(data$address)
data$famsize <- as.factor(data$famsize)
data$Pstatus <- as.factor(data$Pstatus)
data$Mjob <- as.factor(data$Mjob)
data$Fjob <- as.factor(data$Fjob)
data$reason <- as.factor(data$reason)
data$guardian <- as.factor(data$guardian)
data$schoolsup <- as.factor(data$schoolsup)
data$famsup <- as.factor(data$famsup)
data$paid <- as.factor(data$paid)
data$activities <- as.factor(data$activities)
data$nursery <- as.factor(data$nursery)
data$higher <- as.factor(data$higher)
data$internet <- as.factor(data$internet)
data$romantic <- as.factor(data$romantic)
```


```{r}
str(data)
```

# 模型1：预测G1

```{r}
library(dplyr)
data_G1 <- select(data, -c("school", "G2", "G3"))
```

## 带/不带截距全变量预测
Multiple R-squared:  0.3339,	Adjusted R-squared:  0.2628 
```{r}
lm.model <- lm(G1~., data=data_G1)
summary(lm.model)
```


Multiple R-squared:  0.9437,	Adjusted R-squared:  0.9375
```{r}
lm.model <- lm(G1~.-1, data=data_G1)
lm.model
summary(lm.model)
```

## 根据显著性约简模型
```{r}
G1.model <- lm(G1~sex+studytime+failures+schoolsup+goout-1, 
               data=data_G1)
summary(G1.model)
```

## 评估模型
```{r}
library(car)
plot(G1.model)
```


```{r}
AIC(G1.model)

# 检验是否正态
qqPlot(G1.model)

# 检验是否线性
crPlots(G1.model)

# 因变量幂次检验
spreadLevelPlot(G1.model) # 0.46,但是呈水平

# 残差自相关性检验
durbinWatsonTest(G1.model)

# 共线性，无截距，算了吧不看了
vif(G1.model)

# 离群值检验
influencePlot(G1.model)
```

解决异常值,解决因变量不线性
```{r}
data_G1[c(3,79,199,233,249),]
data_G1 <- data_G1[-c(3,79,199,233,249),]
```

```{r}
G1.model2 <- lm(sqrt(sqrt(G1))~sex+studytime+failures+schoolsup+goout-1, 
               data=data_G1)
summary(G1.model2)
AIC(G1.model2)
```


```{r}
AIC(G1.model2)

# 检验是否正态
qqPlot(G1.model2)

# 检验是否线性
crPlots(G1.model2)

# 因变量幂次检验
spreadLevelPlot(G1.model2)

# 残差自相关性检验
durbinWatsonTest(G1.model2)


# 离群值检验
influencePlot(G1.model2)
```

# 2. 预测G2
```{r}
data_G2 <- select(data, -c("school","G3"))
```

```{r}
G2.model <- lm(G2~traveltime+romantic+G1-1, data=data_G2)
summary(G2.model)
```

```{r}
AIC(G2.model)

# 检验是否正态
qqPlot(G2.model)

# 检验是否线性
crPlots(G2.model)

# 因变量幂次检验
spreadLevelPlot(G2.model) # 0.46,但是呈水平

# 残差自相关性检验
durbinWatsonTest(G2.model)

# 离群值检验
influencePlot(G2.model)

```

# 3. 预测G3
```{r}
data_G3 <- select(data, -c("school"))
```

```{r}
G3.model <- lm(G3~famrel+absences+G2-1, data=data_G3)
summary(G3.model)
```

```{r}
AIC(G3.model)

# 检验是否正态
qqPlot(G3.model)

# 检验是否线性
crPlots(G3.model)

# 因变量幂次检验
spreadLevelPlot(G3.model) # 0.46,但是呈水平

# 残差自相关性检验
durbinWatsonTest(G3.model)

# 离群值检验
influencePlot(G3.model)
```
