---
title: "Test"
author: 
date: '2023-03-19'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```
# 没用上的分位点处理
range_capture <- function(x) {
    if (x >= 0 & x < 100) {
        return(0)
    } else if (x < 500) {
        return(1)
    } else if (x < 2500) {
        return(2)
    } else if (x < 15000) {
        return(3)
    } else {
        return(4)
    }
}

# 计算分位点
sample.df$result <- sapply(sample.df$shares, range_capture)

```


```{r}
library(knitr)
library(kableExtra)
library(Hmisc)
library(dplyr)
library(ggplot2)

getwd()
```
# 0  对结果处理
```{r}
sample.df <- read.csv(file="./Data/News2.csv", header = T,
                     na.strings=c("","NA","NULL",NULL), sep = ",")


# 查看结果
head(sample.df)

```

# 1. 数据预处理
```{r}
head(sample.df)
```

## 1.1 数据描述

### 查找缺失值
```{r}
colSums(is.na(sample.df))

sample.df[is.na(sample.df$content.Seg),]

sum(complete.cases(sample.df))
```
```{r}
sample.df <- sample.df[-c(21228,29063,30930,35423),]
sample.df[is.na(sample.df$content.Seg),]
```


### 描述
```{r}
colnames(sample.df)
```


利用Hmisc包中describe进行描述
GMD(Gini mean difference) - 度量变量的离散值
```{r}
desc <- describe(sample.df)

# 将结果存储到文本文件
sink("describe.txt")
cat(capture.output(desc), sep = "\n")
sink()
```

删掉没用的特征
```{r}
sample.df <- dplyr::select(sample.df, -c("url","title","content",
                                        "n_unique_tokens","n_non_stop_words",
                                         "n_non_stop_unique_tokens",
                                         "num_keywords","content.Seg",
                                         "WikiEntity","title.tokens",
                                         "title.tags"))


```

查看类型
```{r}
str(sample.df)

# 转因子变量
# num_hrefs 133
# num_self_hrefs 59
# num_imgs 91
# num_videos 53

sample.df$data_channel_is_lifestyle <- 
  as.factor(sample.df$data_channel_is_lifestyle)
sample.df$data_channel_is_entertainment <- 
  as.factor(sample.df$data_channel_is_entertainment)
sample.df$data_channel_is_bus <- 
  as.factor(sample.df$data_channel_is_bus)
sample.df$data_channel_is_socmed <- 
  as.factor(sample.df$data_channel_is_socmed)
sample.df$data_channel_is_tech <- 
  as.factor(sample.df$data_channel_is_tech)
sample.df$data_channel_is_world <- 
  as.factor(sample.df$data_channel_is_world)

sample.df$weekday_is_monday <- 
  as.factor(sample.df$weekday_is_monday)
sample.df$weekday_is_tuesday <- 
  as.factor(sample.df$weekday_is_tuesday)
sample.df$weekday_is_thursday <- 
  as.factor(sample.df$weekday_is_thursday)
sample.df$weekday_is_wednesday <- 
  as.factor(sample.df$weekday_is_wednesday)
sample.df$weekday_is_friday <- 
  as.factor(sample.df$weekday_is_friday)
sample.df$weekday_is_saturday <- 
  as.factor(sample.df$weekday_is_saturday)
sample.df$weekday_is_sunday <- 
  as.factor(sample.df$weekday_is_sunday)
sample.df$is_weekend <- 
  as.factor(sample.df$is_weekend)

# 大部分全都是发在不是节假日日期的
sample.df$isHoliday <- 
  as.factor(sample.df$isHoliday)

sample.df$topicNo <- 
  as.factor(sample.df$topicNo)

# Flesch.Kincaid.Grade.of.Title 122

sample.df$SyntaxTree.Height <- 
  as.factor(sample.df$SyntaxTree.Height)

# All.Possible.Meanings 这个可能需要归一化

sample.df$noun_count <- 
  as.factor(sample.df$noun_count)
sample.df$verb_count <- 
  as.factor(sample.df$verb_count)

# adverb 和 punc偏态都挺严重，可能需要删去
sample.df$adverb_count <- 
  as.factor(sample.df$adverb_count)
sample.df$punc_count <- 
  as.factor(sample.df$punc_count)



# 考虑删除
# Comparatives.Count 
# Superlatives.Count 
# Count.Intensifiers 
# Count.Downtoners 

```

### 特征分布与异常值
画分布
```{r}

GetDistribution <- function(df){
  df = as.data.frame(df)
  variable.No <- ncol(df) 

  for(i in 1:variable.No){
    # 判断该列是否为数值型变量
    if (class(df[,i][1])[1] == "numeric") {
      TmpFileName <- paste("PlotHistFigures/",i,"-",colnames(df)[i],".png",sep="")
      png(file=TmpFileName)
      hist(df[,i],xlim=c(min(na.omit(df[,i])),max(na.omit(df[,i])) )) #get hist for each column
      dev.off()
    }
  }
}

GetDistribution(sample.df)
```

查看预测值分布
```{r}
hist(log(sample.df$shares))
```

画箱线图
```{r}
# 对于集中于一条线的，例如kw_avg_avg那种，一般是有严重的偏态，一般取对数
# 绘制箱线图，并保存至文件夹内
for (col in names(sample.df)) {
  if (is.numeric(sample.df[[col]][1])){
      filename <- paste0("boxplots/",col, ".png")
      png(filename)
      boxplot(sample.df[[col]], main = col, horizontal = TRUE)
      dev.off()
  }
}
```

根据特征画图
```{r}
ggplot(data = sample.df, aes(x = n_tokens_title, fill=result)) +
  geom_bar()


ggplot(data = sample.df, aes(x = shares)) +
  geom_histogram()

ggplot(data = sample.df, aes(x = shares)) +
  geom_histogram() + scale_x_log10()

ggplot(data = sample.df, aes(x = shares)) +
  geom_histogram() + scale_x_continuous(limits = c(0, 10000))
```

## 2. 先拿随机森林试试水
```{r}
library(randomForest)
set.seed(20021119)
train.forest <- randomForest(logShares~timedelta + n_tokens_title + n_tokens_content +
                 num_hrefs + 
    num_self_hrefs + num_imgs + num_videos + average_token_length + 
    data_channel_is_lifestyle + data_channel_is_entertainment + 
    data_channel_is_bus + data_channel_is_socmed + data_channel_is_tech + 
    data_channel_is_world + is_weekend + topicNo + 
          Comparatives.Count + Superlatives.Count + Count.Intensifiers + 
    Flesch.Kincaid.Grade.of.Title + Count.Downtoners + SyntaxTree.Height + 
    All.Possible.Meanings + noun_count + verb_count + adverb_count + 
    punc_count + title_subjectivity + title_sentiment_polarity + isHoliday, 
    data = sample.df, importance = TRUE, ntree=500)
train.forest
```

```{r}
plot(train.forest[["predicted"]],sample.df$shares)
```

```{r}
importance <- train.forest$importance
importance <- as.data.frame(importance)

#可以根据某种重要性的高低排个序，例如根据“IncNodePurity”指标
importance <- importance[order(importance$IncNodePurity, decreasing = TRUE),]
head(importance)
```

```{r}
sample.df$logShares <- log(sample.df$shares)



```

```{r}
lm.model <- lm(logShares~timedelta + n_tokens_title + n_tokens_content +
                 num_hrefs + 
    num_self_hrefs + num_imgs + num_videos + average_token_length + 
    data_channel_is_lifestyle + data_channel_is_entertainment + 
    data_channel_is_bus + data_channel_is_socmed + data_channel_is_tech + 
    data_channel_is_world + is_weekend + topicNo + 
          Comparatives.Count + Superlatives.Count + Count.Intensifiers + 
    Flesch.Kincaid.Grade.of.Title + Count.Downtoners + SyntaxTree.Height + 
    All.Possible.Meanings + noun_count + verb_count + adverb_count + 
    punc_count + title_subjectivity + title_sentiment_polarity + isHoliday-1,
    data = sample.df)
summary(lm.model)
```


```{r}
library(car)

# 因变量幂次检验
spreadLevelPlot(lm.model)
```